GET http://localhost:3000/shoppingList
###
GET http://localhost:3000/shoppingList/65c2a58a930732be0679726f
###
POST http://localhost:3000/shoppingList 
Content-Type: application/json
###
PATCH http://localhost:3000/shoppingList/65c2a58a930732be0679726f
Content-Type: application/json

{
	"_id": "65c2a58a930732be0679726f",
	"title": "Test list update 1"
}

###
DELETE  http://localhost:3000/shoppingList/65c159fd5108c60ab4565e7f
Content-Type: application/json


